name: pokeapi_wrapper
description: Flutter PokeApi Wrapper for consuming https://pokeapi.co/api/v2 endpoints with auto caching data.
version: 0.0.2
homepage: https://github.com/cbalmeida/pokeapi_wrapper

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: